//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Org.Edgerunner.ANTLR4.Tools.Testing.Grun.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Org.Edgerunner.ANTLR4.Tools.Testing.Grun.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grun.Net.config.
        /// </summary>
        internal static string AppconfigFile {
            get {
                return ResourceManager.GetString("AppconfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &quot;{0}&quot; could not be found..
        /// </summary>
        internal static string FileNotFoundErrorMessage {
            get {
                return ResourceManager.GetString("FileNotFoundErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grammar &quot;{0}&quot; has no parser..
        /// </summary>
        internal static string GrammarHasNoParserErrorMessage {
            get {
                return ResourceManager.GetString("GrammarHasNoParserErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find an assembly that defines grammar &quot;{0}&quot; in the current working directory.
        /// </summary>
        internal static string GrammarNotFoundErrorMessage {
            get {
                return ResourceManager.GetString("GrammarNotFoundErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to continue.
        /// </summary>
        internal static string PressAnyKeyMessage {
            get {
                return ResourceManager.GetString("PressAnyKeyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now reading from standard input.  Use Ctrl+Z to terminate input..
        /// </summary>
        internal static string ReadingFromStandardInputPromptMessage {
            get {
                return ResourceManager.GetString("ReadingFromStandardInputPromptMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing of svg aborted due to missing parser..
        /// </summary>
        internal static string SvgWritingAbortedErrorMessage {
            get {
                return ResourceManager.GetString("SvgWritingAbortedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot display parse tree..
        /// </summary>
        internal static string UnableToDisplayParseTree {
            get {
                return ResourceManager.GetString("UnableToDisplayParseTree", resourceCulture);
            }
        }
    }
}
