//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Org.Edgerunner.ANTLR4.Tools.Testing.GrunWin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Org.Edgerunner.ANTLR4.Tools.Testing.GrunWin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {0}.
        /// </summary>
        internal static string AboutMessage {
            get {
                return ResourceManager.GetString("AboutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files|*.*.
        /// </summary>
        internal static string AllFilesFilter {
            get {
                return ResourceManager.GetString("AllFilesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grun.Net.config.
        /// </summary>
        internal static string AppconfigFile {
            get {
                return ResourceManager.GetString("AppconfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly files|*.dll.
        /// </summary>
        internal static string AssemblyFileFilter {
            get {
                return ResourceManager.GetString("AssemblyFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot set a default rule when a grammar is not loaded.
        /// </summary>
        internal static string CannotLoadDefaultRuleForNonexistentGrammarMessage {
            get {
                return ResourceManager.GetString("CannotLoadDefaultRuleForNonexistentGrammarMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may only load one grammar and one source file at a time..
        /// </summary>
        internal static string DragDropLoadErrorMessage {
            get {
                return ResourceManager.GetString("DragDropLoadErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load file..
        /// </summary>
        internal static string FileLoadFailedMessage {
            get {
                return ResourceManager.GetString("FileLoadFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find file &quot;{0}&quot;..
        /// </summary>
        internal static string FileNotFoundMessage {
            get {
                return ResourceManager.GetString("FileNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading grammars.
        /// </summary>
        internal static string GrammarLoadErrorTitle {
            get {
                return ResourceManager.GetString("GrammarLoadErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while queueing graph work.
        /// </summary>
        internal static string GraphQueueErrorTitle {
            get {
                return ResourceManager.GetString("GraphQueueErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while rendering the graph.
        /// </summary>
        internal static string GraphRenderErrorTitle {
            get {
                return ResourceManager.GetString("GraphRenderErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parser rule &quot;{0}&quot; is invalid.
        /// </summary>
        internal static string InvalidParserRule {
            get {
                return ResourceManager.GetString("InvalidParserRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long.
        /// </summary>
        internal static string Long {
            get {
                return ResourceManager.GetString("Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ms.
        /// </summary>
        internal static string MillisecondsAbbreviation {
            get {
                return ResourceManager.GetString("MillisecondsAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ANTLR4 grammars were found in assembly &quot;{0}&quot;.
        /// </summary>
        internal static string NoGrammarsFoundInAssembly {
            get {
                return ResourceManager.GetString("NoGrammarsFoundInAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading the source.
        /// </summary>
        internal static string SourceLoadErrorTitle {
            get {
                return ResourceManager.GetString("SourceLoadErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while parsing the source.
        /// </summary>
        internal static string SourceParseErrorTitle {
            get {
                return ResourceManager.GetString("SourceParseErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while coloring syntax errors.
        /// </summary>
        internal static string SyntaxErrorColoringErrorTitle {
            get {
                return ResourceManager.GetString("SyntaxErrorColoringErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while coloring grammar tokens.
        /// </summary>
        internal static string TokenColoringErrorTitle {
            get {
                return ResourceManager.GetString("TokenColoringErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        internal static string VersionMessage {
            get {
                return ResourceManager.GetString("VersionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0ms.
        /// </summary>
        internal static string ZeroMilliseconds {
            get {
                return ResourceManager.GetString("ZeroMilliseconds", resourceCulture);
            }
        }
    }
}
